[programs.devnet]
myepicproject = "6Ai67BaED9LKdtg5bCSSaadgqApcpEtND4zQVkKddR8e"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/silvestrevivo/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
